name: example-environment
channels:
          - conda-forge
dependencies:
        - numpy
        - pandas
        - hdf5
        - matplotlib
        - scikit-learn
        - tensorflow
        - keras
